/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Login;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author 영
 */
public class TODO extends javax.swing.JFrame {

    /** Creates new form TODO */
    public TODO() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        PlannedP = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        AssignedP = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TaskP = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Group = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ImportantP = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(65, 65, 85));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 210, 10));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 246, 228));
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        PlannedP.setBackground(new java.awt.Color(89, 89, 112));
        PlannedP.setForeground(new java.awt.Color(89, 89, 112));
        PlannedP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlannedPMouseClicked(evt);
            }
        });
        PlannedP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(235, 246, 228));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_calendar_25px.png"))); // NOI18N
        jLabel2.setText("     Planned");
        PlannedP.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, -1));

        jPanel1.add(PlannedP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 230, 50));

        AssignedP.setBackground(new java.awt.Color(89, 89, 112));
        AssignedP.setForeground(new java.awt.Color(89, 89, 112));
        AssignedP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AssignedPMouseClicked(evt);
            }
        });
        AssignedP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(235, 246, 228));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_user_25px.png"))); // NOI18N
        jLabel5.setText("     Assigned to me");
        AssignedP.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, -1));

        jPanel1.add(AssignedP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 230, 50));

        TaskP.setBackground(new java.awt.Color(89, 89, 112));
        TaskP.setForeground(new java.awt.Color(89, 89, 112));
        TaskP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TaskPMouseClicked(evt);
            }
        });
        TaskP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(235, 246, 228));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_home_25px.png"))); // NOI18N
        jLabel6.setText("     Task");
        TaskP.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, -1));

        jPanel1.add(TaskP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 230, 50));

        Group.setBackground(new java.awt.Color(65, 65, 85));
        Group.setForeground(new java.awt.Color(89, 89, 112));
        Group.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(235, 246, 228));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_plus_25px_1.png"))); // NOI18N
        jLabel3.setText("New List");
        Group.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 120, -1));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(235, 246, 228));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_folder_25px.png"))); // NOI18N
        Group.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jPanel1.add(Group, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 230, 50));

        ImportantP.setBackground(new java.awt.Color(89, 89, 112));
        ImportantP.setForeground(new java.awt.Color(89, 89, 112));
        ImportantP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImportantPMouseClicked(evt);
            }
        });
        ImportantP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(235, 246, 228));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_star_25px.png"))); // NOI18N
        jLabel4.setText("     Important");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        ImportantP.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, -1));

        jPanel1.add(ImportantP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 230, 50));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 210, 10));

        jScrollPane1.setViewportView(jPanel1);

        jPanel2.setBackground(new java.awt.Color(245, 247, 233));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 948, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void setColor(JPanel panel){
        panel.setBackground(new Color(79,79,102));
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(89,89,112));
    }
    
    private void ImportantPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImportantPMouseClicked
        // TODO add your handling code here:
        setColor(ImportantP);
        resetColor(PlannedP);
        resetColor(AssignedP);
        resetColor(TaskP);
    }//GEN-LAST:event_ImportantPMouseClicked

    private void PlannedPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlannedPMouseClicked
        // TODO add your handling code here:
        resetColor(ImportantP);
        setColor(PlannedP);
        resetColor(AssignedP);
        resetColor(TaskP);
    }//GEN-LAST:event_PlannedPMouseClicked

    private void AssignedPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AssignedPMouseClicked
        // TODO add your handling code here:
        resetColor(ImportantP);
        resetColor(PlannedP);
        setColor(AssignedP);
        resetColor(TaskP);
    }//GEN-LAST:event_AssignedPMouseClicked

    private void TaskPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaskPMouseClicked
        // TODO add your handling code here:
        resetColor(ImportantP);
        resetColor(PlannedP);
        resetColor(AssignedP);
        setColor(TaskP);
    }//GEN-LAST:event_TaskPMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        resetColor(ImportantP);
        resetColor(PlannedP);
        resetColor(AssignedP);
        setColor(TaskP);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TODO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TODO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TODO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TODO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TODO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AssignedP;
    private javax.swing.JPanel Group;
    private javax.swing.JPanel ImportantP;
    private javax.swing.JPanel PlannedP;
    private javax.swing.JPanel TaskP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

}
